name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          yarn
      - name: Build Docs
        run: |
          cd example && yarn site
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: example/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
